name: Deploy CloudFormation Stack11

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file templates/mylambda-cfn.yaml \
            --stack-name dp-lambda-cfn \
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-2"